name: Deploy to Lightsail

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

    - name: Copy files via SCP
      uses: appleboy/scp-action@v0.1.1
      with:
        host: 54.145.181.50
        username: ubuntu
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        source: "./*"
        target: "/var/www/crab.codes"

    - name: Restart server or perform any other commands
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.145.181.50 'sudo systemctl restart nginx'
